"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vtqG4HD9Eoa
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import useRoom from "@/lib/useRoom"

export function Room() {
  const events = useRoom()


  return (
    <div className="h-screen w-full flex flex-col">
      <div className="flex-1 overflow-auto p-4">
        <div className="space-y-4">
          {events.map((event) => {
            return (
              <div key={event.time}>
                <div className="font-bold">
                  {event.username} <span className="text-xs text-gray-500">{event.time}</span>
                </div>
                <p>{event.message}</p>
              </div>
            )
          })}
        </div>
        <div className="p-4 border-t">
          <form onSubmit={async (e) => {
            e.preventDefault()

            const data = new FormData(e.currentTarget)
            fetch("/api", {
              method: "POST",
              body: JSON.stringify({
                username: data.get("username"),
                message: data.get("message")
              }),
            })
          }}>
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input name="username" placeholder="Type your username..." />
              <Label htmlFor="message">Message</Label>
              <Input name="message" placeholder="Type your message..." />
              <Button className="w-full" type="submit">
                Send
              </Button>
            </div>
          </form>
        </div>
      </div>
    </div>)
}
